FROM python:3.9-slim-bullseye
WORKDIR /code
COPY .  .
COPY requirements/ requirements/
RUN python -m pip install --upgrade pip
RUN pip install -r requirements/prod.txt
RUN apt-get update \
	&& rm -rf /var/lib/apt/lists/*
CMD gunicorn config.wsgi:application -c gunicorn.conf.py
