# Generated by Django 5.0.7 on 2024-08-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authtoken", "0004_alter_tokenproxy_options"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyToken",
            fields=[],
            options={
                "verbose_name": "Токен",
                "verbose_name_plural": "Токены",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("authtoken.token",),
        ),
    ]
